{% set org_name = "scimma" %}
{% set repo_name = "hop-client" %}

package:
  name: "{{ repo_name|lower }}"
  version: {{ version }}

source:
  git_url: "https://github.com/{{ org_name }}/{{ repo_name }}.git"
  git_tag: "v{{ version }}"

build:
  skip: True    # [not py>=36]
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - hop = hop.__main__:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python
    - adc-streaming ==0.3.1
    - xmltodict >=0.9.0
    - dataclasses    # [py==36]

test:
  imports:
    - hop
    - hop.publish
    - hop.subscribe

about:
  home: "https://github.com/scimma/hop-client"
  license: "BSD"
  license_family: "BSD"
  license_file: ""
  summary: "A pub-sub client library for Multimessenger Astrophysics"
  doc_url: ""
  dev_url: ""
