{% set repo_name = "scimma" %}
{% set pack_name = "client_library" %}

{% set name = "scimma-client" %}
package:
  #name: "{{ pack_name|lower }}"
  name: "{{ name|lower }}"
  version: {{ version }}

source:
  url: "https://pypi.io/packages/source/s/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "c0f87a158f6ea3cd302b13fec00b81445a6edf3e4629a8744078ad120f810f69"

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - scimma = scimma.client.__main__:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python
    - adc >=0.0.3
    - xmltodict >=0.9.0
    - dataclasses

test:
  imports:
    - scimma
    - scimma.client
    - scimma.client.publish

about:
  home: "https://github.com/scimma/client_library"
  license: "BSD"
  license_family: "BSD"
  license_file: ""
  summary: "A client library for SCiMMA"
  doc_url: ""
  dev_url: ""
