version: 2

build:
    os: ubuntu-24.04
    tools:
        python: latest

python:
    install:
      - method: pip
        path: .
        extra_requirements:
          - docs

sphinx:
    configuration: doc/conf.py